### ISSUE TITLE
Last update date wrongly set to future date

### ISSUE THREAD

**Issue by tmo26** [schplurtz/a2s#6]
Today = 2018-05-**03**

From https://www.dokuwiki.org/plugin:a2s: Last updated on 2018-05-**26**

-> Wrong date set for "Last update"

**Comment by schplurtz** [comment]
Hi,
Thank you for reporting this. Obviously, I should have taken more caffeine when I made that change.

Fortunately, it does not prevent the plugin from functioning properly, nor does it cause any problem to DW itself. This same buggy date is also present in file plugin.info.txt. This date, although false and buggy, is not too far in the future, and will soon be reached; its effects (if any) will vanish at that time.

I don't want to fix this because then, DokuWiki extension manager would see it as a new version and would ask admins to update this extension, while there is indeed nothing new.

I'll have the opportunity to correct this, if/when there are changes to a2s.

**Comment by schplurtz** [comment]
Still feeling silly with this issue. Anyway, it's now june 2018, I guess it can be closed.
